<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/damrygcd8/image/upload/v1554540269/fee989f9-7bb6-42e0-b95c-358826a91c38.jpg" alt="Okafor-udah Divine">
                        <h6>Okafor-udah Divine</h6>
                        <p>Front-end Web_Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/crusoeanderson?ref_src=twsrc%5Etfw" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Deeokafor" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@okafor.udahdivine" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Okafor-udah Divine and a software developer. I build the front-end for web and native Apps. look no further, I can help bring your products to life on the interwebs. ;)</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML5 | CSS3</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>